name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # // give  list of  files wityhout checkout 
      - name: List files in the repository
        run: ls -R